# Site settings
title:          Jesper Eriksen 
description:    ""

theme: tale

# Google Analytics
google_analytics: UA-157835857-1

# Author
author:
  name:         Jesper Eriksen
  url:          https://jespereriksen.com
  email:        jesper.eriksen@econ.ku.dk

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-remote-theme
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       20

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale